"(EO01). Identificar diferenças e semelhanças nas formas de organização familiar.",
    "(EO02). Conhecer e reconhecer a existência das normas sociais de convivência.",
    "(EO03). Desenvolver atitudes coletivas para a manutenção do ambiente escolar.",
    "(EO04). Compreender e identificar as relações de parentesco na família.",
    "(EO05). Utilizar o diálogo como forma de comunicação e resolução de conflitos.",
    "(EO06). Diferenciar e descreveráreas urbanas e rurais.",
    "(EO07). Perceber a existência de símbolos, sinais, signose códigos necessários à organização social (sinais de trânsito, mapas, entre outros).",
    "(EO08). Registrar, convencionalmente ou não, semelhanças e diferenças entre objetos, e seres da natureza.",
    "(EO09). Identificar os seres vivos que convivem no cotidiano, e em outros contextos,conhecendo os locais onde habitam.",
    "(EO10). Conhecer e/ou identificar as características do corpo humano.",
    "(EO11). Reconhecer e valorizar atitudes e comportamentos favoráveis à saúde (alimentação, higiene pessoal, espaço onde vive, entre outros).",
    "(EO12). Reconhecer a identidade, a partir do grupo social de pertença, valorizando e respeitando as diferenças.",
    "(EO13). Interagir com diferentes materiais que contemplem a diversidade étnico-racial, de gênero, de geração, e de pessoas com deficiência.",
   "(EO14). Oportunizar o contato com a linguagem de sinais (LIBRAS) e BRAILE, como forma de interação e convívio social.",
    "(EO15) Participar de vivências éticas e estéticas, com outras crianças e grupos culturais, que alarguem padrões de referência, e de identidade no diálogo, e reconhecimento da diversidade.",
    "(EO16). Conhecer, e interagir com as manifestações e tradições culturais brasileiras.",
    "(EO17). Desenvolver a autonomia, compreendendo as normas sociais, reconhecendo suas conquistas e limitações.",
    "(EO18). Interagir com crianças da mesma faixa etária, e com adultos, ao explorar espaços, materiais, objetos e brinquedos.",
    "(EO19). Ampliar relações interpessoais, desenvolvendo atitudes de participação e cooperação.",
    "(EO20). Utilizar o conhecimento tecnológico em situações do cotidiano.",
    "(EO21). Familiarizar-se com as novas tecnologias de forma interativa.",
    "(EO22). Integrar os recursos tecnológicos ao processo de formação.",
                    
                